# Generated by Django 5.0.6 on 2024-07-04 23:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('T31', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='click',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
